# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LNu83TXQ_cYdM06GNgrvMDfkyacfspu3
"""

import streamlit as st
import pandas as pd

# Set up page layout
st.set_page_config(page_title="Friendship Ledger", page_icon="📝", layout="centered")

SHEET_ID = "1ZDK7eQlf7OECJYOVC4L1EaObTPD_2S7y14KyI8sJSM4"
CSV_URL = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/export?format=csv"
BASE_LINK = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/edit?usp=sharing"

@st.cache_data(ttl=30)
def load_data():
    try:
        df = pd.read_csv(CSV_URL)
        # Standardize columns: lowercase and stripped of extra spaces
        df.columns = [str(c).strip().lower() for c in df.columns]
        return df
    except Exception as e:
        return None

df = load_data()

st.title("⚖️ Balanced Account Ledger")
st.write("Select your name below to view any remaining balance details.")

options = ["Select your profile...", "barabad", "esbra", "genoring", "limen", "palmeras"]
selected_name = st.selectbox("Who is logging in?", options)

if selected_name != "Select your profile...":
    st.divider()

    if df is not None:
        try:
            # 1. Safely identify column names from the standardized lowercase list
            name_col = 'name' if 'name' in df.columns else df.columns[0]

            # Look for any column containing 'status' if exact 'status' isn't found
            status_col = 'status'
            if status_col not in df.columns:
                status_col = [c for c in df.columns if 'status' in c][0] if any('status' in c for c in df.columns) else df.columns[-1]

            # Look for any column containing 'cost' or 'individual'
            cost_col = 'cost/individual'
            if cost_col not in df.columns:
                cost_col = [c for c in df.columns if 'cost' in c or 'indiv' in c][0] if any('cost' in c or 'indiv' in c for c in df.columns) else 'cost'

            # 2. Filter rows for the selected person safely
            person_df = df[df[name_col].astype(str).str.strip().str.lower() == selected_name].copy()

            # 3. Filter rows where status is NOT 'paid' (using the dynamic status_col)
            unpaid_df = person_df[person_df[status_col].astype(str).str.strip().str.lower() != 'paid'].copy()

            # 4. Extract numeric values, removing currency symbols (like ₱, $, or commas)
            # Replaced regex to convert empty strings to NaN so they don't break the sum
            unpaid_costs = unpaid_df[cost_col].astype(str).str.replace(r'[^\d\.]', '', regex=True)
            unpaid_numeric = pd.to_numeric(unpaid_costs, errors='coerce').fillna(0)

            total_debt = unpaid_numeric.sum()

            st.subheader(f"Summary for: **{selected_name.upper()}**")

            # Check if there are actually unpaid items rows
            if total_debt > 0:
                st.metric(label="Current Balance Owed", value=f"₱ {total_debt:,.2f}")
                st.caption("Amounts are automatically added up from all unchecked or unpaid line items.")

                # Optional: Show them what items are unpaid so they can verify
                with st.expander("View Unpaid Items Breakdown"):
                    st.dataframe(unpaid_df[[name_col, cost_col, status_col]])
            else:
                st.success("🎉 Balance clear! You have no outstanding amounts.")

        except Exception as e:
            st.warning("⚠️ Connected to sheet, but formatting doesn't match standard layout headers.")
            st.error(f"Developer Error Log: {e}") # This will tell you exactly what failed
            st.info("Ensure headers match exactly: 'Name', 'Cost/Individual', and 'Status'.")
    else:
        st.error("Could not fetch the database records. Please double-check sheet sharing access permissions.")

    st.write("---")
    st.link_button(f"📂 Open Spreadsheet Workspace", BASE_LINK)